<template>
  <div class="background">
    <img id="b1" class="shadow-pop-tr" src="../assets/5.png" alt="" />
    <img id="b2" class="shadow-pop-tr" src="../assets/7.png" alt="" />
    <!-- <img id="b3" class="shadow-pop-tr" src="../assets/8.png" alt="" /> -->
    <!-- <img id="b4" class="shadow-pop-tr" src="../assets/9.png" alt="" /> -->
    <!-- <img id="b5" class="shadow-pop-tr" src="../assets/10.png" alt="" /> -->
    <!-- <img id="b6" class="shadow-pop-tr" src="../assets/11.png" alt="" /> -->
    <!-- <img id="b7" class="shadow-pop-tr" src="../assets/12-1.png" alt="" /> -->
    <!-- <img id="b8" class="shadow-pop-tr" src="../assets/13-1.png" alt="" /> -->
    <!-- <img id="b9" class="shadow-pop-tr" src="../assets/14.png" alt="" /> -->
    <!-- <img id="b10" class="shadow-pop-tr" src="../assets/15.png" alt="" /> -->
    <!-- <img id="t1" class="shadow-pop-tr" src="../assets/20.png" alt="" /> -->
  </div>
</template>

<script>
// < src="https://kit.fontawesome.com/150aa59347.js" crossorigin="anonymous">
export default {
  name: "VillageView",
  data() {
    return {};
  },
  methods: {
    getOwner(event) {
      const id = event.target.id;
      for (const person of this.$store.state.residents) {
        if (person.id === id) {
          this.$router.push({ name: "recommend", params: { id: id } });
        }
      }
    },
  },
};
</script>

<style scoped>
.background {
  height: 100vh;
  width: 100vw;
  overflow: hidden;
  margin: 0;
  padding: 0;
  background-image: url("../assets/배경6.jpg");
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center;
}

img {
  display: inline-block;
  position: absolute;
}

* {
  margin: 0;
  padding: 0;
}

#b1 {
  top: 56.1%;
  left: 0;
  right: 1000px;
  filter: brightness(1.2);
}

#b2 {
  top: 37.6%;
  right: 1045px;
  filter: brightness(1.2);
}

#b3 {
  top: 340px;
  right: 955px;
  filter: brightness(1.3);
}

#b4 {
  top: 418px;
  right: 818px;
}

#b5 {
  top: 359px;
  right: 672px;
}

#b6 {
  top: 311px;
  right: 523px;
}

#b7 {
  top: 380px;
  right: 421px;
}

#b8 {
  top: 386px;
  right: 285px;
}

#b9 {
  top: 330px;
  right: 156px;
}

#b10 {
  top: 390px;
  right: 0px;
  left: 1305px;
}

#t1 {
  top: 491px;
  right: 115px;
  /* filter: brightness(1.4) saturate(1.7) hue-rotate(10deg) sepia(0.3); */
}

/* .shadow-pop-tr:hover {
  animation: shadow-pop-tr 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) both;
} */

/* ----------------------------------------------
 * Generated by Animista on 2022-11-20 15:48:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shadow-pop-tr
 * ----------------------------------------
 */
/* @keyframes shadow-pop-tr {
  0% {
    box-shadow: 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e,
      0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e;
    transform: translateX(0) translateY(0);
  }
  100% {
    box-shadow: 1px -1px #3e3e3e, 2px -2px #3e3e3e, 3px -3px #3e3e3e,
      4px -4px #3e3e3e, 5px -5px #3e3e3e, 6px -6px #3e3e3e, 7px -7px #3e3e3e,
      8px -8px #3e3e3e;
    transform: translateX(-8px) translateY(8px);
  }
} */

img:hover {
  transition: all 0.2s linear;
  transform: scale(1.05);
}
</style>